server:
  port: 3344

spring:
  application:
    name:  microserviceconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shenyoubing/microserviceconfig.git #GitHub上面的git仓库名字


