server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway.com
    prefer-ip-address: true

zuul:
  #ignored-services: microservice-dept
  prefix: /syb
  ignored-services: "*"
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /mydept/**


info:
  app.name: syb-microservice
  company.name: www.syb.com
  build.artifactId: @project.artifactId@
  build.version: @project.version@